// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjf1sYzPI6pVf9DDjkyab0mTPEMY76Ps',
    appId: '1:491942592184:web:5499abae7a0af27e63fe4d',
    messagingSenderId: '491942592184',
    projectId: 'fir-reg-38d0f',
    authDomain: 'fir-reg-38d0f.firebaseapp.com',
    storageBucket: 'fir-reg-38d0f.appspot.com',
    measurementId: 'G-DVL2BXTS9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtcjEoP3En1PEQOxW17WGCGgHAStK36fs',
    appId: '1:491942592184:android:6220f7bac60f66b163fe4d',
    messagingSenderId: '491942592184',
    projectId: 'fir-reg-38d0f',
    storageBucket: 'fir-reg-38d0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBzwDKDOBWHwNnZqb6FqlfrTOQIjdlKg',
    appId: '1:491942592184:ios:f4ff3fd7148dba8863fe4d',
    messagingSenderId: '491942592184',
    projectId: 'fir-reg-38d0f',
    storageBucket: 'fir-reg-38d0f.appspot.com',
    iosClientId: '491942592184-2vtcsms522rd4g7fogivpgp1hcinqic2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpagecheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBzwDKDOBWHwNnZqb6FqlfrTOQIjdlKg',
    appId: '1:491942592184:ios:f4ff3fd7148dba8863fe4d',
    messagingSenderId: '491942592184',
    projectId: 'fir-reg-38d0f',
    storageBucket: 'fir-reg-38d0f.appspot.com',
    iosClientId: '491942592184-2vtcsms522rd4g7fogivpgp1hcinqic2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpagecheck',
  );
}
